language: java
sudo: true
jdk:
  - openjdk11

before_install:
  - openssl aes-256-cbc -K $encrypted_65f6a220a07e_key -iv $encrypted_65f6a220a07e_iv
    -in travis.enc -out ~/.ssh/travis -d
  - chmod 600 ~/.ssh/travis
  - echo "Host $IP" >> ~/.ssh/config
  - echo "  HostName $IP" >> ~/.ssh/config
  - echo "  PreferredAuthentications publickey" >> ~/.ssh/config
  - echo "  IdentityFile ~/.ssh/travis" >> ~/.ssh/config
  - chmod +x ./mvnw

install: cd myspringboot && mvn install -DskipTests=true -Dmaven.javadoc.skip=true

branches:
  only:
    - master

script:
  -"./mvnw test -B"

after_success:
  - cd target
  - scp -o StrictHostKeyChecking=no -r ./*.jar ubuntu@$IP:/home/ubuntu/myspringboot-docker/java
