###############################################################################
## dev
###############################################################################
## 数据库
spring:
  datasource:
    url: jdbc:mysql://58.87.121.239:8706/my_database?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ENC(IdxJT9iGJA3XYxo2iRZ4IQ==)
    password: ENC(MU8IYLJXxxv8ieJJWC8z/DTcsj0rQXvuIZqEeCm92DJRAcxbLnwTHA==)
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 600000
      maximum-pool-size: 10
      pool-name: MyHikariCP
  # redis
  redis:
    database: 0
    host: 58.87.121.239
    port: ENC(nraPi+7zb3yNOcyCHNUoSA==)
    password: ENC(vvYw/azP/VIWPNd0Pr8vGzFmpjDORgZk/eSDTuDGni5NVv2UrZI52g==)
    lettuce:
      pool:
        min-idle: 5
        max-idle: 5
        max-active: 8
        max-wait: 1ms
      shutdown-timeout: 100ms
  # servlet
  servlet:
    multipart:
      max-file-size: 10KB
  # hot
  devtools:
    restart:
      enabled: false
  # banner
  main:
    banner-mode: "off"

###############################################################################
## jasypt 真实环境下，请在命令行等安全地方使用 password
## windows 系统变量要重启电脑才能生效
## 有时候就是无法获取到${}引用的变量值，可能是缓存问题引起的，请清空缓存重启(大坑，)
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
